---
- hosts: all
  become: yes
  tasks:
          - name: Download kubeadm and its dependiences
            get_url: 
              url: http://files.cloudthat.training/devops/kubernetes-ckad/kubeadm-script-v1.18.sh
              dest: /home/ubuntu/kubeadm-script-v1.18.sh
              
          - name: Run the bash script
            become: yes
            become_user: root
            shell: bash /home/ubuntu/kubeadm-script-v1.18.sh
            
          - name: Start the cluster
            become: yes
            become_user: root
            command: "kubeadm init"

          - name: create .kube directory
            become: yes
            become_user: ubuntu
            file:
              path: /home/ubuntu/.kube/
              state: directory
              mode: 0777
              
          - name: copy admin.conf to user's kube config
            copy:
              src: /etc/kubernetes/admin.conf
              dest: /home/ubuntu/.kube/config
              remote_src: yes
              owner: ubuntu
              mode: 0777
              
          - name: install kubectl
            apt:
              name: kubectl=1.14.0-00
              state: present
              force: yes

          - name: providing it network
            shell: export KUBECONFIG=/etc/kubernetes/admin.conf && export kubever=$(kubectl version | base64 | tr -d '\n') && kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
            register: out
            
          - name: inlisting the pods
            shell: kubectl get pods --namespace=kube-system --kubeconfig=/home/ubuntu/.kube/config
            
          - name: inlisting the the nodes
            shell: kubectl get nodes --namespace=kube-system --kubeconfig=/home/ubuntu/.kube/config
            
          - name: Permissions for .kube
            become: yes
            command: chmod 0777 /home/ubuntu/.kube/config

