apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: test
        tier: frontend
    spec:
      containers:
      - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
